version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse-init:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  spark:
    image: bitnami/spark:latest
    volumes:
      - ./spark-app:/opt/spark-app
    command: bash -c "/opt/bitnami/spark/bin/spark-submit --master local /opt/spark-app/app.py"
    depends_on:
      - kafka

  generator:
    build: .
    volumes:
      - ./data-generator:/app
    working_dir: /app
    command: python generate.py
    depends_on:
      - kafka
